id: PBC1DB6EC
initial_creation_type: input
source_metadata:
  title: Drimé Ösal Lingpa Series
  language: fr
  description: 'Texts by and about Tertön Drimé Ösal Lingpa (dri med ''od gsal gling
    pa):'
  volume:
    7b9a862411254acaa6b97c1f899f8352:
      title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab
        Lingpa
      parent: Prayers
created_at: '2022-02-28T23:04:53.524653'
last_modified_at: '2022-02-28T23:04:53.524656'
